# CafeApp/.travis.yml
language: csharp
before_install:
  - chmod +x build.sh
script:
  - ./build.sh RunUnitTests
mono:
  - latest
after_success:
  # notify Docker Hub to make a new build
  - >
    [ "$TRAVIS_BRANCH" == "master" ]
    && curl -X POST -H "Content-Type: application/json"
    --data '{"docker_tag_name": "latest"}'
    https://registry.hub.docker.com/u/lanayx/fscafeapp/trigger/$DOCKER_HUB_TOKEN/
